### ISSUE TITLE
Change the ARRAY "blocked_words" to a YAML file

### ISSUE THREAD

**Issue by falceso** [PluginService/AntiBully#2]
Make a .yml to hold blocked words so you don't have to be a developer.

**Comment by DUFCLiam** [comment]
Ok, I will do this wanna do the PR for it :)

**Comment by DUFCLiam** [comment]
Completed in:
#7cd1088fd1b62f357fbf195f421d993fa82669e5
#c3d260925eb36bf80a1d47677365ba52ef7f3b8f
#739c0decf6b723a3453632d706b8b3c81910a7f5
#2589ed49e5b1721356547d91e684f44bd221995e
